import { create } from 'zustand';

const MOCK_RECIPES = [
  {
    id: '1',
    title: 'Salad Ức Gà Sốt Mè Rang',
    author: 'CookAI',
    time: '15p',
    rating: '4.9',
    difficulty: 'Dễ',
    calories: '350 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800',
    category: 'Healthy',
    ingredients: [
      { id: 'i1', name: 'Ức gà', amount: 200, unit: 'g' },
      { id: 'i2', name: 'Xà lách', amount: 100, unit: 'g' },
      { id: 'i3', name: 'Cà chua bi', amount: 50, unit: 'g' },
      { id: 'i4', name: 'Sốt mè rang', amount: 30, unit: 'ml' },
    ],
    steps: [
      { id: 's1', desc: 'Rửa sạch xà lách và cà chua bi, để ráo nước.', timer: 0 },
      { id: 's2', desc: 'Áp chảo ức gà với một ít muối và tiêu trong 10 phút.', timer: 600 },
      { id: 's3', desc: 'Thái ức gà thành miếng vừa ăn.', timer: 0 },
      { id: 's4', desc: 'Trộn tất cả nguyên liệu với sốt mè rang và thưởng thức.', timer: 0 },
    ],
    isTrending: true,
    matchScore: 0.98,
  },
  {
    id: '2',
    title: 'Pasta Carbonara Ý',
    author: 'Chef Maria',
    time: '20p',
    rating: '4.8',
    difficulty: 'Trung bình',
    calories: '600 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?q=80&w=400',
    category: 'Món Âu',
    ingredients: [
      { id: 'i5', name: 'Mì Spaghetti', amount: 100, unit: 'g' },
      { id: 'i6', name: 'Trứng gà', amount: 2, unit: 'quả' },
      { id: 'i7', name: 'Thịt ba chỉ xông khói', amount: 50, unit: 'g' },
      { id: 'i8', name: 'Phô mai Parmesan', amount: 30, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Luộc mì spaghetti trong nước sôi 8-10 phút.', timer: 540 },
      { id: 's2', desc: 'Chiên thịt ba chỉ xông khói cho đến khi giòn.', timer: 300 },
      { id: 's3', desc: 'Đánh tan trứng với phô mai Parmesan.', timer: 0 },
      { id: 's4', desc: 'Trộn mì nóng với hỗn hợp trứng và thịt.', timer: 0 },
    ],
    isTrending: true,
  },
  {
    id: '3',
    title: 'Bò Kho Bánh Mì',
    author: 'Bếp Mẹ',
    time: '120p',
    rating: '5.0',
    difficulty: 'Khó',
    calories: '750 kcal',
    imageUrl: 'https://statics.vinpearl.com/bo-kho-nha-trang-2_1695732113.jpg',
    category: 'Món Việt',
    ingredients: [
      { id: 'i9', name: 'Thịt bò nạm', amount: 500, unit: 'g' },
      { id: 'i10', name: 'Cà rốt', amount: 2, unit: 'củ' },
      { id: 'i11', name: 'Sả', amount: 3, unit: 'nhánh' },
      { id: 'i12', name: 'Gia vị bò kho', amount: 1, unit: 'gói' },
    ],
    steps: [
      { id: 's1', desc: 'Ướp thịt bò với gia vị trong 30 phút.', timer: 1800 },
      { id: 's2', desc: 'Xào săn thịt bò với sả và tỏi.', timer: 300 },
      { id: 's3', desc: 'Hầm thịt bò với nước dừa trong 90 phút.', timer: 5400 },
      { id: 's4', desc: 'Cho cà rốt vào hầm thêm 15 phút.', timer: 900 },
    ],
    isTopRated: true,
  },
  {
    id: '4',
    title: 'Gà Chiên Nước Mắm',
    author: 'Dương Chef',
    time: '30p',
    rating: '4.7',
    difficulty: 'Trung bình',
    calories: '500 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i13', name: 'Cánh gà', amount: 500, unit: 'g' },
      { id: 'i14', name: 'Nước mắm', amount: 3, unit: 'muỗng' },
      { id: 'i15', name: 'Tỏi băm', amount: 1, unit: 'muỗng' },
      { id: 'i16', name: 'Đường', amount: 2, unit: 'muỗng' },
    ],
    steps: [
      { id: 's1', desc: 'Rửa sạch cánh gà, để ráo và chiên vàng.', timer: 900 },
      { id: 's2', desc: 'Phi thơm tỏi, cho nước mắm và đường vào nấu sệt.', timer: 120 },
      { id: 's3', desc: 'Cho cánh gà đã chiên vào đảo đều cho thấm sốt.', timer: 180 },
    ],
    isTrending: true,
  },
  {
    id: '5',
    title: 'Phở Bò Gia Truyền',
    author: 'Phở Thìn',
    time: '180p',
    rating: '5.0',
    difficulty: 'Khó',
    calories: '450 kcal',
    imageUrl: 'https://monngonmoingay.com/wp-content/uploads/2019/03/pho-bo-bap-hoa-500.jpg',
    category: 'Món Việt',
    ingredients: [
      { id: 'i17', name: 'Bánh phở', amount: 500, unit: 'g' },
      { id: 'i18', name: 'Thịt bò phi lê', amount: 200, unit: 'g' },
      { id: 'i19', name: 'Xương ống bò', amount: 1000, unit: 'g' },
      { id: 'i20', name: 'Quế, hồi, thảo quả', amount: 1, unit: 'bộ' },
    ],
    steps: [
      { id: 's1', desc: 'Hầm xương ống bò trong 3-5 tiếng để lấy nước dùng.', timer: 10800 },
      { id: 's2', desc: 'Nướng hành tím, gừng và rang các loại gia vị khô.', timer: 300 },
      { id: 's3', desc: 'Cho gia vị vào nồi nước dùng hầm tiếp 1 tiếng.', timer: 3600 },
      { id: 's4', desc: 'Chần bánh phở, xếp thịt bò và chan nước dùng.', timer: 0 },
    ],
    isTopRated: true,
  },
  {
    id: '6',
    title: 'Bún Chả Hà Nội',
    author: 'Cô Liên',
    time: '60p',
    rating: '4.9',
    difficulty: 'Trung bình',
    calories: '600 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1555126634-323283e090fa?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i21', name: 'Thịt ba chỉ', amount: 500, unit: 'g' },
      { id: 'i22', name: 'Bún tươi', amount: 1, unit: 'kg' },
      { id: 'i23', name: 'Nước mắm', amount: 5, unit: 'muỗng' },
      { id: 'i24', name: 'Đu đủ, cà rốt', amount: 200, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Thái mỏng thịt ba chỉ, ướp với gia vị, nước mắm, hành tỏi băm.', timer: 1800 },
      { id: 's2', desc: 'Làm đồ chua từ đu đủ và cà rốt thái mỏng, ngâm giấm đường.', timer: 900 },
      { id: 's3', desc: 'Pha nước mắm chua ngọt với tỏi ớt băm nhỏ.', timer: 300 },
      { id: 's4', desc: 'Nướng thịt trên than hoa cho đến khi chín vàng.', timer: 1200 },
    ],
    isTrending: true,
  },
  {
    id: '7',
    title: 'Sushi Cá Hồi',
    author: 'Chef Ken',
    time: '45p',
    rating: '4.8',
    difficulty: 'Khó',
    calories: '400 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=400',
    category: 'Món Á',
    ingredients: [
      { id: 'i25', name: 'Gạo Nhật', amount: 300, unit: 'g' },
      { id: 'i26', name: 'Cá hồi tươi', amount: 200, unit: 'g' },
      { id: 'i27', name: 'Lá rong biển', amount: 5, unit: 'lá' },
      { id: 'i28', name: 'Giấm sushi', amount: 3, unit: 'muỗng' },
    ],
    steps: [
      { id: 's1', desc: 'Vo gạo, nấu cơm chín và trộn đều với giấm sushi khi cơm còn nóng.', timer: 1800 },
      { id: 's2', desc: 'Thái mỏng cá hồi thành từng lát vừa ăn.', timer: 0 },
      { id: 's3', desc: 'Nắm cơm thành từng vắt nhỏ, đặt lát cá hồi lên trên.', timer: 600 },
    ],
    isTopRated: true,
  },
  {
    id: '8',
    title: 'Salad Bơ Trứng',
    author: 'Healthy Life',
    time: '15p',
    rating: '4.7',
    difficulty: 'Dễ',
    calories: '320 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=400',
    category: 'Healthy',
    ingredients: [
      { id: 'i29', name: 'Bơ sáp', amount: 1, unit: 'quả' },
      { id: 'i30', name: 'Trứng gà', amount: 2, unit: 'quả' },
      { id: 'i31', name: 'Xà lách', amount: 100, unit: 'g' },
      { id: 'i32', name: 'Dầu oliu', amount: 2, unit: 'muỗng' },
    ],
    steps: [
      { id: 's1', desc: 'Luộc chín trứng gà, bóc vỏ và thái múi cau.', timer: 480 },
      { id: 's2', desc: 'Bơ lột vỏ, bỏ hạt, thái lát mỏng.', timer: 0 },
      { id: 's3', desc: 'Rửa sạch xà lách, để ráo nước.', timer: 0 },
      { id: 's4', desc: 'Trộn bơ, trứng, xà lách với dầu oliu và một ít muối tiêu.', timer: 0 },
    ],
    isTrending: false,
  },
  {
    id: '9',
    title: 'Súp Bí Đỏ Kem Tươi',
    author: 'Chef Maria',
    time: '30p',
    rating: '4.9',
    difficulty: 'Trung bình',
    calories: '380 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?q=80&w=400',
    category: 'Khai vị',
    ingredients: [
      { id: 'i33', name: 'Bí đỏ', amount: 400, unit: 'g' },
      { id: 'i34', name: 'Kem tươi (Whipping cream)', amount: 100, unit: 'ml' },
      { id: 'i35', name: 'Hành tây', amount: 0.5, unit: 'củ' },
      { id: 'i36', name: 'Bơ nhạt', amount: 20, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Gọt vỏ bí đỏ, thái miếng nhỏ. Thái mỏng hành tây.', timer: 0 },
      { id: 's2', desc: 'Xào hành tây với bơ cho thơm, thêm bí đỏ vào xào sơ.', timer: 300 },
      { id: 's3', desc: 'Thêm nước hoặc nước hầm xương vào ninh mềm bí đỏ.', timer: 900 },
      { id: 's4', desc: 'Xay nhuyễn hỗn hợp, đun sôi lại và thêm kem tươi vào khuấy đều.', timer: 300 },
    ],
    isTrending: true,
  },
  {
    id: '10',
    title: 'Đậu Phụ Sốt Tứ Xuyên',
    author: 'Bếp Hoa',
    time: '20p',
    rating: '4.6',
    difficulty: 'Trung bình',
    calories: '450 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=400',
    category: 'Món Á',
    ingredients: [
      { id: 'i37', name: 'Đậu phụ non', amount: 2, unit: 'hộp' },
      { id: 'i38', name: 'Thịt heo băm', amount: 100, unit: 'g' },
      { id: 'i39', name: 'Sa tế Tứ Xuyên', amount: 2, unit: 'muỗng' },
      { id: 'i40', name: 'Tỏi, hành lá', amount: 50, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Thái đậu phụ thành các khối vuông nhỏ, chần qua nước sôi.', timer: 120 },
      { id: 's2', desc: 'Phi thơm tỏi, xào thịt băm chín tới.', timer: 300 },
      { id: 's3', desc: 'Cho sa tế, xì dầu, một ít nước vào đun sôi làm sốt.', timer: 180 },
      { id: 's4', desc: 'Cho đậu phụ vào lắc nhẹ chảo để ngấm sốt, rắc hành lá.', timer: 120 },
    ],
    isTopRated: false,
  },
  {
    id: '11',
    title: 'Canh Chua Cá Lóc',
    author: 'Mẹ Nấu',
    time: '40p',
    rating: '4.8',
    difficulty: 'Trung bình',
    calories: '300 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i41', name: 'Cá lóc', amount: 500, unit: 'g' },
      { id: 'i42', name: 'Cà chua, thơm (dứa)', amount: 200, unit: 'g' },
      { id: 'i43', name: 'Giá đỗ, bạc hà', amount: 150, unit: 'g' },
      { id: 'i44', name: 'Nước cốt me', amount: 3, unit: 'muỗng' },
    ],
    steps: [
      { id: 's1', desc: 'Cá lóc làm sạch, thái khúc, ướp sơ gia vị.', timer: 600 },
      { id: 's2', desc: 'Phi thơm tỏi, xào sơ cà chua và thơm.', timer: 180 },
      { id: 's3', desc: 'Thêm nước, nấu sôi, cho cá vào đun chín cùng nước cốt me.', timer: 600 },
      { id: 's4', desc: 'Nêm nếm chua ngọt, cho giá, bạc hà, rau ôm ngò gai vào rồi tắt bếp.', timer: 60 },
    ],
    isTrending: false,
  },
  {
    id: '12',
    title: 'Bò Bít Tết',
    author: 'Gordon R.',
    time: '25p',
    rating: '5.0',
    difficulty: 'Khó',
    calories: '650 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=400',
    category: 'Món Âu',
    ingredients: [
      { id: 'i45', name: 'Thịt bò thăn lườn', amount: 300, unit: 'g' },
      { id: 'i46', name: 'Bơ nhạt', amount: 30, unit: 'g' },
      { id: 'i47', name: 'Tỏi nguyên tép', amount: 4, unit: 'tép' },
      { id: 'i48', name: 'Nhánh hương thảo', amount: 2, unit: 'nhánh' },
    ],
    steps: [
      { id: 's1', desc: 'Thấm khô bề mặt thịt, rắc đều muối tiêu lên 2 mặt.', timer: 0 },
      { id: 's2', desc: 'Làm nóng chảo, cho chút dầu ăn, áp chảo thịt mỗi mặt 2-3 phút.', timer: 300 },
      { id: 's3', desc: 'Cho bơ, tỏi, hương thảo vào chảo, liên tục rưới bơ chảy lên miếng thịt.', timer: 120 },
      { id: 's4', desc: 'Lấy thịt ra, để nghỉ 5 phút trước khi thái.', timer: 300 },
    ],
    isTopRated: true,
  },
  {
    id: '13',
    title: 'Nem Rán Truyền Thống',
    author: 'Hà Nội Xưa',
    time: '60p',
    rating: '4.8',
    difficulty: 'Trung bình',
    calories: '550 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i49', name: 'Thịt lợn băm', amount: 300, unit: 'g' },
      { id: 'i50', name: 'Bánh đa nem', amount: 20, unit: 'tờ' },
      { id: 'i51', name: 'Miến, mộc nhĩ, nấm hương', amount: 100, unit: 'g' },
      { id: 'i52', name: 'Trứng gà', amount: 2, unit: 'quả' },
    ],
    steps: [
      { id: 's1', desc: 'Ngâm mềm miến, mộc nhĩ, nấm hương rồi thái nhỏ.', timer: 900 },
      { id: 's2', desc: 'Trộn đều thịt băm, rau củ, miến, nấm, trứng và gia vị.', timer: 300 },
      { id: 's3', desc: 'Trải bánh đa nem, cho nhân vào cuộn tròn vừa tay.', timer: 600 },
      { id: 's4', desc: 'Chiên nem ngập dầu với lửa vừa đến khi vàng giòn.', timer: 900 },
    ],
    isTrending: false,
  },
  {
    id: '14',
    title: 'Gỏi Cuốn Tôm Thịt',
    author: 'Quán Cô Năm',
    time: '30p',
    rating: '4.7',
    difficulty: 'Dễ',
    calories: '280 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?q=80&w=400',
    category: 'Healthy',
    ingredients: [
      { id: 'i53', name: 'Tôm tươi', amount: 200, unit: 'g' },
      { id: 'i54', name: 'Thịt ba chỉ', amount: 200, unit: 'g' },
      { id: 'i55', name: 'Bánh tráng cuốn', amount: 20, unit: 'cái' },
      { id: 'i56', name: 'Rau sống, bún tươi', amount: 300, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Luộc chín thịt ba chỉ, thái mỏng. Luộc tôm, bóc vỏ, chẻ đôi.', timer: 1200 },
      { id: 's2', desc: 'Rửa sạch rau sống, để ráo.', timer: 0 },
      { id: 's3', desc: 'Làm ướt bánh tráng, xếp rau, bún, thịt, tôm và cuộn chặt tay.', timer: 600 },
      { id: 's4', desc: 'Pha nước chấm tương đậu phộng hoặc mắm nêm để ăn kèm.', timer: 300 },
    ],
    isTrending: true,
  },
  {
    id: '15',
    title: 'Mì Ý Hải Sản',
    author: 'Pasta Lover',
    time: '25p',
    rating: '4.6',
    difficulty: 'Trung bình',
    calories: '550 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?q=80&w=400',
    category: 'Món Âu',
    ingredients: [
      { id: 'i57', name: 'Mì Ý', amount: 200, unit: 'g' },
      { id: 'i58', name: 'Tôm, mực', amount: 250, unit: 'g' },
      { id: 'i59', name: 'Sốt cà chua chua ngọt', amount: 200, unit: 'ml' },
      { id: 'i60', name: 'Tỏi băm, lá basil', amount: 20, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Luộc mì Ý chín tới, vớt ra trộn chút dầu oliu.', timer: 480 },
      { id: 's2', desc: 'Phi thơm tỏi, xào hải sản cho săn lại.', timer: 180 },
      { id: 's3', desc: 'Đổ sốt cà chua vào nấu sôi, nêm nếm gia vị vừa ăn.', timer: 240 },
      { id: 's4', desc: 'Cho mì vào trộn đều với sốt và hải sản, trang trí lá basil.', timer: 60 },
    ],
    isTopRated: false,
  },
  {
    id: '16',
    title: 'Cơm Rang Dưa Bò',
    author: 'Hà Thành Quán',
    time: '20p',
    rating: '4.7',
    difficulty: 'Trung bình',
    calories: '650 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i61', name: 'Cơm nguội', amount: 2, unit: 'chén' },
      { id: 'i62', name: 'Thịt bò', amount: 150, unit: 'g' },
      { id: 'i63', name: 'Dưa chua', amount: 100, unit: 'g' },
      { id: 'i64', name: 'Trứng gà', amount: 1, unit: 'quả' },
    ],
    steps: [
      { id: 's1', desc: 'Trộn đều cơm với trứng gà, đánh tơi.', timer: 0 },
      { id: 's2', desc: 'Xào thịt bò với dưa chua trên lửa lớn, trút ra đĩa.', timer: 300 },
      { id: 's3', desc: 'Rang cơm trên chảo dầu nóng cho đến khi hạt cơm săn, giòn.', timer: 480 },
      { id: 's4', desc: 'Trút phần dưa bò lên trên cơm rang và thưởng thức nóng.', timer: 0 },
    ],
    isTrending: false,
  },
  {
    id: '17',
    title: 'Cháo Sườn Quẩy',
    author: 'Cháo Ngõ Huyện',
    time: '90p',
    rating: '4.8',
    difficulty: 'Trung bình',
    calories: '400 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i65', name: 'Bột gạo tẻ', amount: 100, unit: 'g' },
      { id: 'i66', name: 'Sườn non', amount: 300, unit: 'g' },
      { id: 'i67', name: 'Quẩy giòn', amount: 5, unit: 'cái' },
      { id: 'i68', name: 'Ruốc (chà bông)', amount: 50, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Ninh sườn non lấy nước ngọt, gỡ thịt sườn xé nhỏ.', timer: 3600 },
      { id: 's2', desc: 'Hòa bột gạo tẻ với nước lạnh cho tan, đổ từ từ vào nồi nước hầm.', timer: 300 },
      { id: 's3', desc: 'Khuấy đều tay liên tục trên lửa nhỏ đến khi cháo sánh mịn.', timer: 1200 },
      { id: 's4', desc: 'Múc cháo ra tô, rắc sườn, ruốc, tiêu và ăn kèm quẩy cắt nhỏ.', timer: 0 },
    ],
    isTopRated: true,
  },
  {
    id: '18',
    title: 'Gà Hầm Sâm',
    author: 'Seoul Kitchen',
    time: '120p',
    rating: '4.9',
    difficulty: 'Khó',
    calories: '550 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=400',
    category: 'Món Á',
    ingredients: [
      { id: 'i69', name: 'Gà ta nguyên con nhỏ', amount: 1, unit: 'con' },
      { id: 'i70', name: 'Nhân sâm tươi', amount: 1, unit: 'củ' },
      { id: 'i71', name: 'Gạo nếp', amount: 50, unit: 'g' },
      { id: 'i72', name: 'Táo đỏ, hạt dẻ, tỏi', amount: 50, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Ngâm gạo nếp 2 tiếng. Làm sạch gà, nhồi gạo nếp, táo đỏ, tỏi vào bụng.', timer: 7200 },
      { id: 's2', desc: 'Khâu kín bụng gà lại. Đun sôi nồi nước với nhân sâm, hành tây.', timer: 600 },
      { id: 's3', desc: 'Thả gà vào nồi hầm nhỏ lửa trong 1.5 - 2 tiếng đến khi chín mềm.', timer: 5400 },
      { id: 's4', desc: 'Múc ra thố đá, rắc hành lá. Chấm thịt gà với muối tiêu.', timer: 0 },
    ],
    isTrending: false,
  },
  {
    id: '19',
    title: 'Bún Bò Huế',
    author: 'O Nữ',
    time: '180p',
    rating: '5.0',
    difficulty: 'Khó',
    calories: '650 kcal',
    imageUrl: 'https://file.hstatic.net/200000700229/article/bun-bo-hue-1_da318989e7c2493f9e2c3e010e722466.jpg',
    category: 'Món Việt',
    ingredients: [
      { id: 'i73', name: 'Xương ống, móng giò bò', amount: 1, unit: 'kg' },
      { id: 'i74', name: 'Bún sợi to', amount: 1, unit: 'kg' },
      { id: 'i75', name: 'Sả, mắm ruốc Huế', amount: 100, unit: 'g' },
      { id: 'i76', name: 'Chả cua, tiết luộc', amount: 200, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Hầm xương bò và xương heo với sả đập dập trong 2-3 tiếng.', timer: 7200 },
      { id: 's2', desc: 'Lọc mắm ruốc lấy nước trong, cho vào nồi hầm.', timer: 600 },
      { id: 's3', desc: 'Phi dầu điều với hành sả băm và ớt bột, thêm vào nồi nước dùng.', timer: 300 },
      { id: 's4', desc: 'Trụng bún, xếp móng giò, thịt bò bắp, chả cua, chan nước dùng.', timer: 0 },
    ],
    isTopRated: true,
  },
  {
    id: '20',
    title: 'Bánh Xèo Miền Tây',
    author: 'Út Hương',
    time: '45p',
    rating: '4.8',
    difficulty: 'Trung bình',
    calories: '450 kcal',
    imageUrl: 'https://mia.vn/media/uploads/blog-du-lich/thuong-thuc-banh-xeo-mien-tay-1713968410.jpg',
    category: 'Món Việt',
    ingredients: [
      { id: 'i77', name: 'Bột bánh xèo', amount: 1, unit: 'gói' },
      { id: 'i78', name: 'Tôm, thịt ba chỉ', amount: 300, unit: 'g' },
      { id: 'i79', name: 'Giá đỗ, đậu xanh', amount: 200, unit: 'g' },
      { id: 'i80', name: 'Nước cốt dừa', amount: 200, unit: 'ml' },
    ],
    steps: [
      { id: 's1', desc: 'Pha bột với nước cốt dừa, nước, hành lá thái nhỏ và chút bột nghệ.', timer: 300 },
      { id: 's2', desc: 'Xào sơ tôm, thịt ba chỉ và hành tây.', timer: 180 },
      { id: 's3', desc: 'Tráng một lớp bột mỏng vào chảo nóng, thêm nhân tôm thịt, giá đỗ.', timer: 120 },
      { id: 's4', desc: 'Đậy nắp đun chín rồi gập đôi bánh, vớt ra ăn kèm rau sống và nước mắm chua ngọt.', timer: 180 },
    ],
    isTrending: true,
  },
  {
    id: '21',
    title: 'Canh Rong Biển Đậu Phụ',
    author: 'Healthy Diet',
    time: '15p',
    rating: '4.5',
    difficulty: 'Dễ',
    calories: '150 kcal',
    imageUrl: 'https://cdn.tgdd.vn/News/Thumb/1547009/canh-rong-bien-dau-phu-cho-be-1200x628.jpg',
    category: 'Healthy',
    ingredients: [
      { id: 'i81', name: 'Rong biển khô', amount: 20, unit: 'g' },
      { id: 'i82', name: 'Đậu phụ non', amount: 1, unit: 'hộp' },
      { id: 'i83', name: 'Tỏi băm', amount: 1, unit: 'muỗng' },
      { id: 'i84', name: 'Dầu mè', amount: 1, unit: 'muỗng' },
    ],
    steps: [
      { id: 's1', desc: 'Ngâm rong biển trong nước 15 phút cho nở, rửa sạch.', timer: 900 },
      { id: 's2', desc: 'Thái đậu phụ thành các khối nhỏ.', timer: 0 },
      { id: 's3', desc: 'Xào rong biển với dầu mè và tỏi cho thơm.', timer: 120 },
      { id: 's4', desc: 'Đổ nước vào nấu sôi, nêm gia vị, thả đậu phụ vào đun sôi lại tắt bếp.', timer: 300 },
    ],
    isTrending: false,
  },
  {
    id: '22',
    title: 'Sườn Xào Chua Ngọt',
    author: 'Bếp Cơm',
    time: '35p',
    rating: '4.7',
    difficulty: 'Trung bình',
    calories: '500 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=400',
    category: 'Món Việt',
    ingredients: [
      { id: 'i85', name: 'Sườn thăn', amount: 500, unit: 'g' },
      { id: 'i86', name: 'Giấm gạo', amount: 3, unit: 'muỗng' },
      { id: 'i87', name: 'Đường', amount: 3, unit: 'muỗng' },
      { id: 'i88', name: 'Hành, tỏi băm', amount: 30, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Luộc sơ sườn non để loại bỏ bọt bẩn, rửa sạch.', timer: 300 },
      { id: 's2', desc: 'Chiên sườn vàng đều các mặt.', timer: 480 },
      { id: 's3', desc: 'Pha nước sốt: mắm, đường, giấm, tương cà, nước lọc.', timer: 120 },
      { id: 's4', desc: 'Phi hành tỏi, trút sườn và sốt vào rim trên lửa nhỏ đến khi sệt lại.', timer: 600 },
    ],
    isTrending: true,
  },
  {
    id: '23',
    title: 'Cá Hồi Áp Chảo Măng Tây',
    author: 'Chef David',
    time: '20p',
    rating: '4.9',
    difficulty: 'Dễ',
    calories: '450 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=400',
    category: 'Healthy',
    ingredients: [
      { id: 'i89', name: 'Cá hồi phi lê', amount: 200, unit: 'g' },
      { id: 'i90', name: 'Măng tây', amount: 150, unit: 'g' },
      { id: 'i91', name: 'Chanh vàng', amount: 0.5, unit: 'quả' },
      { id: 'i92', name: 'Bơ lạt', amount: 20, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Ướp cá hồi với muối, tiêu và chút nước cốt chanh.', timer: 300 },
      { id: 's2', desc: 'Măng tây cắt bỏ gốc già, chần sơ qua nước sôi.', timer: 120 },
      { id: 's3', desc: 'Áp chảo cá hồi với bơ, mỗi mặt 2-3 phút cho xém vàng.', timer: 300 },
      { id: 's4', desc: 'Xào nhanh măng tây trên cùng chảo, rưới bơ lên cá và thưởng thức.', timer: 180 },
    ],
    isTopRated: true,
  },
  {
    id: '24',
    title: 'Cà Ri Gà Cốt Dừa',
    author: 'Thai Spice',
    time: '45p',
    rating: '4.8',
    difficulty: 'Trung bình',
    calories: '600 kcal',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=400',
    category: 'Món Á',
    ingredients: [
      { id: 'i93', name: 'Thịt gà đùi', amount: 500, unit: 'g' },
      { id: 'i94', name: 'Sốt cà ri', amount: 3, unit: 'muỗng' },
      { id: 'i95', name: 'Nước cốt dừa', amount: 200, unit: 'ml' },
      { id: 'i96', name: 'Khoai tây, cà rốt', amount: 300, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Ướp gà với sốt cà ri và gia vị trong 30 phút.', timer: 1800 },
      { id: 's2', desc: 'Chiên sơ khoai tây và cà rốt cắt miếng.', timer: 300 },
      { id: 's3', desc: 'Xào săn thịt gà, thêm nước dão dừa nấu sôi.', timer: 300 },
      { id: 's4', desc: 'Thêm khoai, cà rốt vào hầm mềm, cuối cùng cho nước cốt dừa vào khuấy đều.', timer: 1200 },
    ],
    isTrending: false,
  },
  {
    id: '25',
    title: 'Lẩu Thái Tomyum',
    author: 'Bangkok Street',
    time: '40p',
    rating: '5.0',
    difficulty: 'Trung bình',
    calories: '500 kcal',
    imageUrl: 'https://thichlaunuong.com/uploads/files/2021/05/21/lau-thai-tomyum-231713.jpg',
    category: 'Món Á',
    ingredients: [
      { id: 'i97', name: 'Tôm sú, mực', amount: 500, unit: 'g' },
      { id: 'i98', name: 'Nghêu, nấm các loại', amount: 400, unit: 'g' },
      { id: 'i99', name: 'Gia vị Tomyum', amount: 1, unit: 'gói' },
      { id: 'i100', name: 'Sả, riềng, lá chanh', amount: 50, unit: 'g' },
    ],
    steps: [
      { id: 's1', desc: 'Rửa sạch hải sản, cắt thái vừa ăn.', timer: 0 },
      { id: 's2', desc: 'Đun sôi nước hầm xương (hoặc nước lọc), đập dập riềng, sả, lá chanh thả vào.', timer: 600 },
      { id: 's3', desc: 'Hòa tan gói gia vị tomyum, thêm một ít nước cốt dừa nếu thích vị béo.', timer: 180 },
      { id: 's4', desc: 'Nhúng hải sản và nấm vào nước lẩu sôi sục và ăn kèm với bún.', timer: 0 },
    ],
    isTopRated: true,
  }

];

export const useRecipeStore = create((set, get) => ({
  recipes: MOCK_RECIPES,
  categories: ['Tất cả', 'Healthy', 'Món Âu', 'Món Việt', 'Món Á', 'Đồ chay', 'Khai vị'],
  
  getRecipeById: (id) => get().recipes.find(r => r.id === id),
  
  getTrendingRecipes: () => get().recipes.filter(r => r.isTrending),
  
  getTopRatedRecipes: () => get().recipes.filter(r => r.isTopRated),

  searchRecipesByIngredients: (selectedIngredients) => {
    if (!selectedIngredients || selectedIngredients.length === 0) return [];
    
    return get().recipes.map(recipe => {
      const matchCount = recipe.ingredients.filter(ing => 
        selectedIngredients.some(selected => selected.toLowerCase() === ing.name.toLowerCase())
      ).length;
      
      const score = matchCount / recipe.ingredients.length;
      return { ...recipe, matchScore: score };
    })
    .filter(r => r.matchScore > 0)
    .sort((a, b) => b.matchScore - a.matchScore);
  },

  searchRecipesByName: (query) => {
    if (!query) return [];
    const lowerQuery = query.toLowerCase();
    return get().recipes.filter(r => r.title.toLowerCase().includes(lowerQuery));
  }
}));
