services:
  db:
    image: postgres:15-alpine
    container_name: mixicook-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./mixicook.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mixicook-network
    restart: always

  app:
    build:
      context: ./mixicook
      dockerfile: Dockerfile
    container_name: mixicook-be
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8083
      APP_JWT_SECRET: ${JWT_SECRET}
      ML_SERVICE_URL: ${ML_SERVICE_URL}
    networks:
      - mixicook-network
    restart: always

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: mixicook-npm
    restart: always
    ports:
      - '80:80' # HTTP
      - '81:81' # Admin UI
      - '443:443' # HTTPS
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - mixicook-network

networks:
  mixicook-network:
    driver: bridge

volumes:
  postgres_data:
