server {
    listen 80;
    server_name kenato26.id.vn;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kenato26.id.vn;

    ssl_certificate /etc/letsencrypt/live/kenato26.id.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kenato26.id.vn/privkey.pem;

    # Tối ưu SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://app:8083;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Cho phép upload file lớn nếu cần
        client_max_body_size 10M;
    }
}
